### ISSUE TITLE
Camunda Cloud website have some misspellings

### ISSUE THREAD

**Issue by aivinog1** [camunda-cloud/issues#27]
**Describe the bug**

**To Reproduce**

1. Go to https://camunda.com/products/cloud/
2. Scroll down to Choose your Camunda Cloud Plan
3. See that some of the words are glued together, for example:
> ... and monitorprocesses...
> ... enterprise processautomation...

**Expected behavior**
Expected to see:
> ... and monitor processes ...
> ... enterprise process automation ...

**Observed behaviour**
![image](https://user-images.githubusercontent.com/25925932/92699832-435cc600-f378-11ea-8a29-b0f51fd90dad.png)

**Scenario**
- Environment: production

**System information (please complete the following information as applicable):**
 - OS:
```
a.i.vinogradov@MacBookPro-aivinogradov ~ % sw_vers -productVersion
10.15.6
a.i.vinogradov@MacBookPro-aivinogradov ~ % 
```
 - Browser version: Google Chrome 85.0.4183.83

**Additional information**

**Comment by ultraschuppi** [comment]
Hello @aivinog1 

thanks for reaching out!

/assign @skalpins - i guess you can route this ;-)

**Comment by felix-mueller** [comment]
This has been fixed.
