### ISSUE TITLE
Docs - Welcome Page - Webinar Link 

### ISSUE THREAD

**Issue by Diznik** [camunda-cloud/issues#28]
The Camunda Cloud Welcome page offers a webinar to help users get started but that webinar link is no longer functioning. https://vimeo.com/389681995

Not sure who sourced it but can we update it?

**Comment by urbanisierung** [comment]
@ultraschuppi I guess it's the camunda cloud welcome page: https://docs.cloud.camunda.io/docs/welcome

How do we want to proceed? If the webinar is available somewhere else we can point to the other target, otherwise I'd suggest to remove the sentence.

**Comment by ultraschuppi** [comment]
> @ultraschuppi I guess it's the camunda cloud welcome page: https://docs.cloud.camunda.io/docs/welcome
> 
> How do we want to proceed? If the webinar is available somewhere else we can point to the other target, otherwise I'd suggest to remove the sentence.

who provided the webinar?

**Comment by urbanisierung** [comment]
It was the very first Camunda Cloud Webinar with Daniel and Immi I guess. A nice introduction to Camunda Cloud.

**Comment by ultraschuppi** [comment]
i reached out to @Charley-Mann to find the video
